name: 'Setup XVFB and FluxBox'
description: 'Setup requirements for running tests on headless Linux'
env:
  DISPLAY: :99
runs:
  using: "composite"
  steps:
    - name: Setup Fluxbox
      run: sudo apt-get -y install fluxbox
      shell: bash
    - name: Start Fluxbox
      run: fluxbox -display :99 &
      shell: bash
    - name: Start XVFB
      run: Xvfb :99 &
      shell: bash
