name: 'Run bazel'
description: 'Simple action to run bazel commands'
inputs:
  command:  # id of input
    description: 'Bazel command to run'
    required: true
runs:
  using: "composite"
  steps:
    - run: copy .github\.bazelrc.windows.local .
      if: runner.os == 'Windows'
      shell: cmd
    - run: bazel ${{ inputs.command }}
      if: runner.os == 'Windows'
      shell: cmd
    - run: cp .github/.bazelrc.local .
      if: runner.os != 'Windows'
      shell: bash
    - run: bazel ${{ inputs.command }}
      if: runner.os != 'Windows'
      shell: bash
